### PR TITLE
Change file naming rules: replace ` ` with `_`

### PR DESCRIPTION
**Pull request by zincnode**
- Update file naming rules
- Add `.gitignore` rules for tests output
- Update tests

For code review, you can just focus on: https://github.com/thuml/depyf/pull/69/commits/05cc7bbfa36450d2eb62f45873bc04197a976816

### CODE REVIEW

**Comment by zincnode** [comment]
File names containing spaces are not friendly to Linux users, so I would like to replace the ` ` in the file name with `_`.

**Comment by youkaichao** [comment]
Hi, thanks for your interest! `torch.compile` internally uses `_` a lot, like `__compiled_fn_1` , so I added https://github.com/thuml/depyf/pull/70 to use mixed dot and underscore. underscore is only used for separating strings, and dot is used to create the hierarchy.

the change looks like:

> rename tests/depyf_output/multiprocessing/{__compiled_fn_1 Captured Graph 0.py => __compiled_fn_1.Captured_Graph.0.py}

Hope it works for your Linux machine.

**Comment by youkaichao** [comment]
> Add .gitignore rules for tests output

You can create another pr for this change 👍

**Comment by zincnode** [comment]
> Hi, thanks for your interest! `torch.compile` internally uses `_` a lot, like `__compiled_fn_1` , so I added #70 to use mixed dot and underscore. underscore is only used for separating strings, and dot is used to create the hierarchy.
> 
> the change looks like:
> 
> > rename tests/depyf_output/multiprocessing/{__compiled_fn_1 Captured Graph 0.py => __compiled_fn_1.Captured_Graph.0.py}
> 
> Hope it works for your Linux machine.

Thanks for the quick response. Better idea.

**Comment by zincnode** [comment]
> > Add .gitignore rules for tests output
> 
> You can create another pr for this change 👍

OK, I'll close this PR.

**Pull request closed without merging**
